---
title: "flexdashboard"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---
```{r}
library(plotly)
library(tidyverse)
library(dplyr)
library(rnoaa)

ny_noaa = read_csv("./data/nynoaadat.csv", na = c("NA", "", "."))

```
### Problem 2 in P8105 homework 4

I am going to focus on ny_noaa data. <br>
variables: <br>
id: Weather station ID <br>
date: Date of observation <br>
prcp: Precipitation (tenths of mm) <br>
snow: Snowfall (mm) <br>
snwd: Snow depth (mm) <br>
tmax: Maximum temperature (tenths of degrees C) <br>
tmin: Minimum temperature (tenths of degrees C) <br>

```{r}
# Data cleaning: Choose entries with nonzero snowfall and restrict it to a maximum of 200 inches of snowfall.

ny_noaa_df= 
  ny_noaa %>%
  janitor::clean_names() %>%
  drop_na() %>%
  separate(col = date, into = c ("year", "month", "day") , sep = "-", convert = TRUE) %>%
  mutate(snowfall = snow*25.4,
         month = month.abb[month],
         tmax = as.numeric(tmax) / 10,
         tmin = as.numeric(tmin) / 10) %>%
  filter(snow > 0, snow < 200, year == 2000) %>%
  select(id, year, month, day, snowfall, tmax, tmin)
```

### Chart A: box plot
```{r}
ny_noaa_df %>% 
  mutate(month = fct_reorder(month, snowfall)) %>% 
  plot_ly(y = ~snowfall, color = ~month, type = "box", colors = "viridis") %>%
  layout(xaxis = list(title = 'Month'),
         yaxis = list(title = 'Snowfall (mm)'))
```
### Chart B: bar plot
```{r}
ny_noaa_df %>% 
  count(id) %>% 
  mutate(id = fct_reorder(id, n)) %>% 
  plot_ly(x = ~id, y = ~n, color = ~id, type = "bar", colors = "viridis") %>%
  layout(xaxis = list(title = 'Weather station ID'),
         yaxis = list(title = 'Number Snowy Days'))
```

### Chart B: scatterplot
```{r}
ny_noaa_df %>%
  plot_ly(x = ~tmin, y = ~tmax, color = ~month, opacity=0.5, colors = "viridis") %>%
  layout(xaxis = list(title = 'Mininum Temperature'),
         yaxis = list(title = 'Maximum Temperature'))
```

